services:
  cyber-bank-api:
    build: ./cyberBank
    command: ["bash", "./run.sh"]
    #restart: unless-stopped
    environment:
      DEBUG: ${DEBUG}
    env_file:
      - .env
    # depends_on:
    #   - cyber-bank-db
    volumes:
      - ./cyberBank:/app
  
  cyber-bank-front:
    build: ./front
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      WDS_SOCKET_HOST: "127.0.0.1"
      API_HOST: ${API_HOST}
    ports:
      - "0.0.0.0:80:80"

