services:
  cyber-bank-api:
    build: ./cyberBank
    command: sh -c "npm run start"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "0.0.0.0:8000:8000"
    # depends_on:
    #   - cyber-bank-db
    volumes:
      - ./cyberBank:/app
