services:
  cyber-bank-back:
    build: ./cyberBank
    command: sh -c "npm run start"
    restart: unless-stopped
    mem_limit: 1G
    memswap_limit: 1G
    cpu_count: 1
    pids_limit: 128
    logging:
      options:
        max-file: "2"
        max-size: "5m"
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    volumes:
      - ./secrets:/usr/rusi-trainer/secrets
    env_file:
      - .env
    depends_on:
      - rusi-db


volumes:
  baikaldata: